In [2]:
import tensorflow as tf

In [5]:
print("Tensorflow version:",tf.__version__)

Tensorflow version: 2.18.0-dev20240620


In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 25s 2us/step


## Build a tf.keras.Sequential model:

In [8]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

C:\Users\dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.28562775, -0.48491773,  0.5410102 ,  0.40305313, -0.7164651 ,
        -0.18987297,  0.43306506,  0.07282414, -0.4902683 , -0.1274627 ]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.07509968, 0.06153009, 0.17164944, 0.14953001, 0.04881212,
        0.08264638, 0.15408571, 0.10747607, 0.06120175, 0.08796873]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1],predictions).numpy()

2.4931843

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=20)

Epoch 1/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8626 - loss: 0.4769
Epoch 2/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9561 - loss: 0.1493
Epoch 3/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9664 - loss: 0.1083
Epoch 4/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9728 - loss: 0.0870
Epoch 5/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9766 - loss: 0.0736
Epoch 6/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9788 - loss: 0.0644
Epoch 7/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9812 - loss: 0.0586
Epoch 8/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9822 - loss: 0.0536
Epoch 9/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9844 - loss: 0.0463
Epoch 10/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9853 - loss: 0.0443
Epoch 11/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9878 - loss: 0.0386
Epoch 12/20
1875/1875 ━━━━━━━━

In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9818 - loss: 0.0778


[0.07781191915273666, 0.9818000197410583]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.08200726e-13, 1.17339130e-16, 5.25683247e-11, 1.97711724e-05,
        1.63668577e-16, 1.89049970e-10, 8.52311449e-23, 9.99974966e-01,
        1.18140081e-10, 5.30390980e-06],
       [1.16842029e-12, 6.57434214e-08, 9.99999881e-01, 4.37218404e-13,
        8.25003595e-31, 1.04164888e-09, 8.96773792e-16, 3.70588981e-26,
        1.62427504e-15, 1.20173589e-27],
       [1.81145168e-11, 9.99987364e-01, 1.80738468e-07, 3.67870318e-10,
        1.02156745e-08, 1.83381851e-11, 4.33994529e-08, 7.21370907e-06,
        5.13580108e-06, 3.72713735e-11],
       [9.99992251e-01, 8.24833590e-16, 7.70424595e-06, 3.41583567e-11,
        7.04827310e-13, 4.04373840e-10, 3.38290320e-08, 4.78427686e-10,
        2.31255553e-13, 1.21718330e-10],
       [1.97611288e-10, 1.92367965e-18, 9.99239233e-12, 4.10801027e-15,
        9.99990225e-01, 2.04943874e-14, 5.19407517e-10, 4.28132182e-07,
        1.54738784e-13, 9.39141682e-06]], dtype=float32)>